#!/usr/bin/env python
"""Look up TMDB posters for the films in _data/favorites.yml.

1. Get a free API key: create a TMDB account, then Settings → API
   (https://www.themoviedb.org/settings/api). Either the "API Key" or the
   "API Read Access Token" works.
2. Run from the repository root:

       TMDB_API_KEY=your_key python scripts/fetch_posters.py

   It writes _data/posters.yml, which the page reads. Commit that file.
   Films already in posters.yml are skipped; pass --force to refresh them.
   If TMDB picks the wrong film, add  tmdb_id: <number>  to that entry in
   favorites.yml (the number in the film's TMDB URL) and run again.

Posters are loaded from TMDB's image server; the page carries the
attribution TMDB asks for. Standard library + pyyaml only.
"""
import argparse
import json
import os
import sys
import urllib.parse
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
FAVS = ROOT / "_data" / "favorites.yml"
OUT = ROOT / "_data" / "posters.yml"
API = "https://api.themoviedb.org/3"


def key_for(film):
    return f"{film['title']} ({film['year']})"


def tmdb(path, params, token):
    params = dict(params)
    headers = {"accept": "application/json"}
    if token.startswith("ey"):            # v4 read-access token
        headers["Authorization"] = f"Bearer {token}"
    else:                                  # v3 API key
        params["api_key"] = token
    url = f"{API}{path}?{urllib.parse.urlencode(params)}"
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=20) as r:
        return json.load(r)


def find(film, token):
    if film.get("tmdb_id"):
        m = tmdb(f"/movie/{film['tmdb_id']}", {}, token)
        return m["id"], m.get("poster_path")
    for params in ({"query": film["title"], "primary_release_year": film["year"]},
                   {"query": film["title"], "year": film["year"]},
                   {"query": film["title"]}):
        res = tmdb("/search/movie", params, token).get("results", [])
        res = [m for m in res if m.get("poster_path")]
        if res:
            return res[0]["id"], res[0]["poster_path"]
    return None, None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true", help="refresh posters already in posters.yml")
    args = ap.parse_args()
    token = os.environ.get("TMDB_API_KEY")
    if not token:
        sys.exit("Set TMDB_API_KEY (see the top of this script).")

    films = yaml.safe_load(FAVS.read_text()) or []
    posters = (yaml.safe_load(OUT.read_text()) if OUT.exists() else None) or {}
    for film in films:
        k = key_for(film)
        if k in posters and not args.force:
            print(f"have    {k}")
            continue
        tid, path = find(film, token)
        if path:
            posters[k] = {"tmdb_id": tid, "poster": path}
            print(f"found   {k}  → https://www.themoviedb.org/movie/{tid}")
        else:
            print(f"MISSING {k}  (add tmdb_id to favorites.yml)")
    OUT.write_text("# Generated by scripts/fetch_posters.py — maps \"Title (Year)\" to a TMDB poster path.\n"
                   + yaml.safe_dump(posters, sort_keys=True, allow_unicode=True))
    print(f"wrote {OUT.relative_to(ROOT)} — check each link above is the right film.")


if __name__ == "__main__":
    main()
