#!/usr/bin/env python
"""Turn the decade spreadsheets in films/ into _data/decades.yml.

Put either of these in films/:
  * the whole workbook as .xlsx, one tab per decade (tab named "1970s" etc.)
  * one CSV per decade, with the decade in the file name

Each sheet needs a header row with Rank, Film, Year, Director; anything
above that row (like a "1970s" title line) is ignored.

    python scripts/import_films.py

A tab whose name isn't a decade (e.g. "Worst") becomes a bonus list in
_data/film_bonus.yml, shown quietly under the decades.

Replace the file and re-run whenever a list changes, then commit
_data/decades.yml (and _data/film_bonus.yml). Decades are listed newest first. Needs pyyaml, plus
openpyxl for .xlsx files.
"""
import csv
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "films"
OUT = ROOT / "_data" / "decades.yml"
BONUS = ROOT / "_data" / "film_bonus.yml"
BONUS_TITLES = {"worst": "Bonus: So Bad It's Good"}  # tab name -> heading on the page
DECADE = re.compile(r"(1[89]|20)\d0s")


def cell(v):
    if v is None:
        return ""
    if isinstance(v, float) and v.is_integer():
        v = int(v)
    return str(v).strip()


def parse(rows, decade_hint, name):
    rows = [[cell(c) for c in r] for r in rows]
    m = DECADE.search(decade_hint) or next((DECADE.search(c) for r in rows[:3] for c in r if DECADE.search(c)), None)
    try:
        h = next(i for i, r in enumerate(rows) if r and r[0].lower() == "rank")
    except StopIteration:
        sys.exit(f"{name}: no header row starting with 'Rank'")
    header = [c.lower() for c in rows[h]]
    col = {k: header.index(k) for k in ("rank", "film", "year", "director")}
    films = []
    for r in rows[h + 1:]:
        if len(r) <= col["film"] or not r[col["film"]]:
            continue
        films.append({
            "rank": int(r[col["rank"]]) if r[col["rank"]].isdigit() else len(films) + 1,
            "title": r[col["film"]],
            "year": int(r[col["year"]]) if r[col["year"]].isdigit() else r[col["year"]],
            "director": r[col["director"]],
        })
    films.sort(key=lambda f: f["rank"])
    if not m:  # not a decade: a bonus list
        title = BONUS_TITLES.get(decade_hint.lower()) or (rows[0][0] if rows and rows[0] and rows[0][0] else decade_hint)
        return {"bonus": title, "films": films}
    return {"decade": m.group(0), "films": films}


def read_file(path):
    if path.suffix.lower() == ".csv":
        rows = list(csv.reader(path.read_text(encoding="utf-8-sig").splitlines()))
        return [parse(rows, path.stem, path.name)]
    import openpyxl
    wb = openpyxl.load_workbook(path, data_only=True, read_only=True)
    return [parse(ws.iter_rows(values_only=True), ws.title, f"{path.name} [{ws.title}]")
            for ws in wb.worksheets]


def main():
    files = sorted(f for f in SRC.iterdir() if f.suffix.lower() in (".csv", ".xlsx") and not f.name.startswith("~$"))
    if not files:
        sys.exit("No .xlsx or .csv files in films/")
    decades, bonus = {}, []
    for f in files:
        for d in read_file(f):
            if "bonus" in d:
                bonus.append(d)
                print(f"{d['bonus']}: {len(d['films'])} films  ({f.name})")
                continue
            decades[d["decade"]] = d  # a later file for the same decade replaces the earlier one
            print(f"{d['decade']}: {len(d['films'])} films  ({f.name})")
    out = [decades[k] for k in sorted(decades, reverse=True)]
    OUT.write_text("# Generated by scripts/import_films.py from films/ — edit the spreadsheet, not this file.\n"
                   + yaml.safe_dump(out, sort_keys=False, allow_unicode=True, width=1000))
    print(f"wrote {OUT.relative_to(ROOT)}")
    BONUS.write_text("# Generated by scripts/import_films.py from films/ — edit the spreadsheet, not this file.\n"
                     + yaml.safe_dump(bonus, sort_keys=False, allow_unicode=True, width=1000))
    print(f"wrote {BONUS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
